name: Update Github Release with PNPM Artifact

on:
  workflow_call:
    inputs:
      cache-key:
        description: 'Artifact Cache Key'
        type: string
        required: true
      cache-path:
        description: 'Artifact Cache Path'
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  update-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: xc2/ghwf/pnpm-artifact/restore@main
        with:
          cache-key: ${{ inputs.cache-key }}
          cache-path: ${{ inputs.cache-path }}
      - name: Update Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ inputs.cache-path }}
